---
- name: playbook for creating Organizations
  hosts: localhost
  gather_facts: False
  vars:
    galaxy_credential:
      - hub1-rh-certified
  collections:
    - ansible.tower



  tasks:
  - name: create Organizatoin
    tower_organization:
      name: "Alex_Org"
      description: "Alex Test Organization"
      state: present
      tower_password: 'xPhrngm'
      tower_username: 'admin'
      validate_certs: no
      galaxy_credentials: "{{ galaxy_credential }}"
      custom_virtualenv: '/var/lib/awx/customEnv/venv'
