---
- name: playbook for creating Organizations
  hosts: localhost
  gather_facts: False
  vars:
    galaxy_credential:
      - hub1-rh-certified
      - automaton_hub
  collections:
    - ansible.tower



  tasks:
  - name: create Organizatoin
    tower_organization:
      name: "Alex_Org"
      description: "Alex Test Organization"
      state: present
      tower_password: 'xPhrngm'
      tower_username: 'admin'
      validate_certs: yes
      max_hosts: 5
      galaxy_credentials: "{{ galaxy_credential }}"
      tower_host: tower.devhomeit.ca

